In [8]:
import tensorflow as tf 
from numpy import array
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
import warnings
warnings.filterwarnings('ignore')


In [9]:
X=array([1,2,3,4,5,6,7,8,9,10])

In [10]:
model=Sequential()
model.add(Dense(units=1,input_shape=(1,)))
model.compile(optimizer='sgd',loss='mean_squared_error')
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(X,X,epochs=50,verbose=0)

In [22]:
model.predict([1]),model.predict([2]),model.predict([3]),model.predict([4])


(array([[1.000564]], dtype=float32),
 array([[2.0004694]], dtype=float32),
 array([[3.0003748]], dtype=float32),
 array([[4.0002804]], dtype=float32))